### ISSUE TITLE
Replace utils by eggshell defined functions

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#252]
See branch https://github.com/bird-house/flyingpigeon/tree/eggshell_dep

**Comment by huard** [comment]
@cehbrecht @nilshempelmann 
Moving utilities from FP to eggshell brings a lot of changes and I've hit some issues. 
Since our test coverage is not so extensive, I'm expecting some breakage. 
One issue that has come up is the config file, which uses _PATH that is set relative to the file. If we import config from another package, a lot of things break. 
I haven't spent a lot of time on this, but maybe a config class with properties would solve the issue.

**Comment by tomLandry** [comment]
We advanced quite a bit on environment and config management in the last spring. Can't recall everything, but maybe updating doc on how it is done in PAVICS could help refactor FP and Eggshell.

**Comment by nilshempelmann** [comment]
Extensivation of tests is a good start 


Envoyé depuis mon smartphone. 
-------- Message d'origine --------De : David Huard <notifications@github.com> Date : 01/06/2018  20:34  (GMT+01:00) À : bird-house/flyingpigeon <flyingpigeon@noreply.github.com> Cc : Nils Hempelmann <info@nilshempelmann.de>, Mention <mention@noreply.github.com> Objet : Re: [bird-house/flyingpigeon] Replace utils by eggshell defined functions (#252) 
@cehbrecht @nilshempelmann

Moving utilities from FP to eggshell brings a lot of changes and I've hit some issues.

Since our test coverage is not so extensive, I'm expecting some breakage.

One issue that has come up is the config file, which uses _PATH that is set relative to the file. If we import config from another package, a lot of things break.

I haven't spent a lot of time on this, but maybe a config class with properties would solve the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/bird-house/flyingpigeon/issues/252#issuecomment-393987285","url":"https://github.com/bird-house/flyingpigeon/issues/252#issuecomment-393987285","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bird-house/flyingpigeon","title":"bird-house/flyingpigeon","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bird-house/flyingpigeon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@huard in #252: @cehbrecht @nilshempelmann \r\nMoving utilities from FP to eggshell brings a lot of changes and I've hit some issues. \r\nSince our test coverage is not so extensive, I'm expecting some breakage. \r\nOne issue that has come up is the config file, which uses _PATH that is set relative to the file. If we import config from another package, a lot of things break. \r\nI haven't spent a lot of time on this, but maybe a config class with properties would solve the issue. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/bird-house/flyingpigeon/issues/252#issuecomment-393987285"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [bird-house/flyingpigeon] Replace utils by eggshell defined functions (#252)",
"sections": [
{
"text": "",
"activityTitle": "**David Huard**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@huard",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"bird-house/flyingpigeon\",\n\"issueId\": 252,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"bird-house/flyingpigeon\",\n\"issueId\": 252\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/bird-house/flyingpigeon/issues/252#issuecomment-393987285"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341587728\n}"
}
],
"themeColor": "26292E"
}

**Comment by tomLandry** [comment]
What's this long string of code in @nilshempelmann reply? The GitHub page itself?

**Comment by nilshempelmann** [comment]
Cleaned up now. Was replying from a mobile phone email

**Comment by tomLandry** [comment]
That's a bug in GitHub if you ask me. This code should never have make it to the thread input.

**Comment by huard** [comment]
Just added a Path class to eggshell. 
https://github.com/bird-house/eggshell/blob/3929811bde32a249615356331b3f5b9ecf0aaa97/eggshell/config.py#L7

The idea is that you would do 

```
from eggshell.config import Paths
import flyingpigeon

paths = Paths(flyingpigeon)
path.data
'/home/david/src/flyingpigeon/flyingpigeon/data'
```
So you may use the Paths class in any bird.

**Comment by nilshempelmann** [comment]
@huard: have a look on `fp_dev` branch in eggshell. What do you think about the structure?

**Comment by huard** [comment]
I don't see that branch...

**Comment by nilshempelmann** [comment]
@huard 
Sorry! Its pushed now.
https://github.com/bird-house/eggshell/tree/fp_dev

**Comment by huard** [comment]
Looks good ! I suggest you go ahead and merge.

**Comment by nilshempelmann** [comment]
DONE
