### ISSUE TITLE
Add time checks in subset processes

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#286]
To catch empty outputs as soon as possible.

**Comment by huard** [comment]
@cehbrecht, @nilshempelmann  
For the bbox subsetting there are start and end parameters. Let's say that these parameters are outside the domain of the resource being subsetted, should we raise an InvalidParameterValue error ?

If there are multiple resources being subsetted, we might want to rather continue processing and only subset those that can be subsetted, and ignore the others. 

Thoughts ?

**Comment by nilshempelmann** [comment]
@huard 
Here my thoughts:

- User should make the decission depending on the usecase. 
- ESGF search could be an orientation (the default): here the time stamp needs to be covered by the data resource to be found. (@cehbrecht am I right :-)?  )
- Time evaluation was (initially) included in the robustness process: (meanwile disabled):
https://github.com/bird-house/flyingpigeon/blob/1.0.x/flyingpigeon/robustness.py#L110 
- skip datasets, modify the choosen time periode or abord the whole process depends on the usecase since this decission modifies the final result. 
- handling of timeseries which coveres historical runs and rcps. Are you seeing the combinaton as one timeseries or seperate 
- there are time check functions in eggshell to be used and improved

Hope this is inspiring

**Comment by cehbrecht** [comment]
I think in ESGF search datasets are returned that partially overlap the [start, end] time interval. If you want to leave the decision to the user you could add an option like: "partial overlap", "full overlap".

**Comment by nilshempelmann** [comment]
@huard: Is that still an issue? 
subset by timerange is more useful for multiple files (an entire dataset). The subset functions are now looping over single files (5year timeslices for daily datafiles). 
Should be the time_range a seperate process?

**Comment by huard** [comment]
It's been a while, I don't know. Ok with closing this.

**Comment by nilshempelmann** [comment]
Outdated
