### ISSUE TITLE
Dockerhub does not build releases

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#296]
## Description

DockerHub does not seem to auto-build releases. My guess is that the regex is wrong since we're using a v before the version number.

**Comment by tlvu** [comment]
I might not have enough permissions on github.com/bird-house/flyingpigeon repo?

I am unable to reconfigure the docker build config.

![2019-10-02-163426_1105x562_scrot](https://user-images.githubusercontent.com/11966697/66079687-8ee4de00-e532-11e9-901a-c808f6fba4b2.png)

**Comment by tlvu** [comment]
Should we agree if we want tag version to be prefixed with `v` or not?  The same problem (no autobuild from docker hub) happended before but this time the `v` was removed from the tag !  See https://github.com/bird-house/finch/issues/38

**Comment by huard** [comment]
I suggest we keep the v and modify the regexp. 
I had the same problem. Do you think it's because it's Carsten's ssh key that is connected ?

**Comment by tlvu** [comment]
> Do you think it's because it's Carsten's ssh key that is connected ?

Should not relate to ssh key but I am unsure on this one.  Do you have admin on the flyingpigeon repo or the entire bird-house org on github?  I was admin on the entire Ouranosinc org so that might have helped.

**Comment by huard** [comment]
Yes, I'm an owner.

**Comment by tlvu** [comment]
If you are already owner of the entire bird-house org on github, then I don't have other ideas.

@davidcaron you where able to configure the Finch which has the same setup (bird-house github and birdhouse docker hub) can you try to edit the docker build config of this Flyingpigeon to see if you have permissions?

**Comment by fmigneault** [comment]
This works for magpie, no `v` in version tag
![image](https://user-images.githubusercontent.com/19194484/66138510-bf795600-e5cc-11e9-9d89-56322851916a.png)

**Comment by Zeitsperre** [comment]
It looks as though I have build control of the repo. I recall that the controls were passed to me by my predecessor left, this was in early 2018 when we were more actively working on the Ouranos fork of FP.

![Screenshot from 2019-10-04 09-09-55](https://user-images.githubusercontent.com/10819524/66210049-daa89c00-e686-11e9-8b74-8966354684ec.png)

Right off the bat, it looks like the regex is wrong. @tlvu I'll see if I can pass this to you or at least we can fix the regex pattern

**Comment by tlvu** [comment]
@davidcaron can you still do the test.  What @fmigneault replied is not a good test since magpie is under Ouranosinc github paired with pavics docker hub.  Have to compare apple with apple.

What we need is bird-house github paired with birdhouse docker hub.  Your Finch and this Flyingpigeon is in this scenario.  You were able to configure Finch so I wonder if you can configure this Flyingpigon as well.

If you can, then we can drill down to what permissions you have that David and I are missing.  If you can not, then it's something else, but at least we can eliminate missing permissions as the possible cause.

**Comment by huard** [comment]
@tlvu 
It seems @Zeitsperre has the permissions. I think we can fix this on our end.

**Comment by huard** [comment]
Scrap that, we only have the permission for the pavics fork.

**Comment by fmigneault** [comment]
I got the permissions. For some reason, the github link was broken. I re-linked it. Now the build rules are defined like in my above example for branch master & regex tag.

**Comment by huard** [comment]
Can you modify the build rules so that it will work with or without v ? It seems the default in most projects is to use v for tags.

**Comment by huard** [comment]
Wait, I now have permissions too to change it ! I'll try it myself.

**Comment by huard** [comment]
Added a rule that includes "v" on dockerhub. 
In the github webhooks config, I checked branch and tag as an event that triggers the webhook. 
Deleted and pushed the 1.5 tag. 
Build has now started on dockerhub.

**Comment by tlvu** [comment]
I also have access now, probably what Francis did fixed it.

I removed "Build Caching" for the Tag builds.  This ensure every layer is rebuilt from scratch instead of reusing an existing layer that might not be up-to-date.  The price to pay is the build is slower.

Ex: a layer with "conda update -n base conda" might not actually update to the latest conda if a layer with the same "text" existed on the build host and is being reused.  I assume the build host are being flushed from time to time but I'd rather not rely on luck.

![2019-10-07-135740_1104x967_scrot](https://user-images.githubusercontent.com/11966697/66336386-f623d900-e90a-11e9-8bcb-f6806b5f34b7.png)
